title: Portafolio de Iker Castaño
author: Iker Castano Cabello
email: iker.castano@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Hola soy Iker y me gusta el deporte. Además quiero aprender mucho.

# social links
twitter_username: ikercasta_
github_username:  iker.castano

show_excerpts: false
theme: minima
